### PR TITLE
added an example to run the server with compose

### PR DESCRIPTION
**Pull request by aadityadhruv**
This is a example to run the container with docker compose. It has some workarounds to running the container in detached mode without the server crashing.

### CODE REVIEW

**Review by JRodez — CHANGES_REQUESTED** [review]
This is a good idea but using `environment` instead of `command` would be better.

**Comment by aadityadhruv** [comment]
Ah, do they work as a ENV variables? I thought they were CLI flags to pass to the entrypoint script I can change it to ENV variables if that seems like a better idea!

**Comment by JRodez** [comment]
There is my docker-compose.yml for example :
```yaml
version: '3'

services:
  terraria:
    container_name: terraria-server
    image: ryshe/terraria:latest
    ports:
      - '7777:7777'
    restart: on-failure
    environment:
      - WORLD_FILENAME=world.wld
      
    volumes:
      - ~/terraria-server/config:/root/.local/share/Terraria/Worlds
    tty: true
    stdin_open: true
`

**Comment by aadityadhruv** [comment]
Done!

**Review by JRodez — APPROVED** [review]

**Review by ryansheehan — APPROVED** [review]

**Pull request merged**
